config/routes.rb
Rails.application.routes.draw do
  resources :actividads

  resources :tipos

  resources :tipo_actividads

  get 'sessions/new'

  get 'static_pages/home'
  get 'ayuda' => 'static_pages#ayuda'
  get 'acerca_de' => 'static_pages#acerca_de'

  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :cenurs

  resources :sedes

  resources :facultads

  resources :caracters

  resources :usuarios do
    resources :actividads, shallow: true
  end

  root 'static_pages#home'

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to  :usuario
  belongs_to  :tipo
  belongs_to  :tipo_actividad, :foreign_key => 'actividad_id'
validates :tipo_id, presence: true
validates :actividad_id, presence: true
validates :usuario_id, presence: true
validates :nombre, presence: true
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController
  include Authentication

  before_action :set_actividad, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :usuario_actividad_o_admin,  only: [:edit, :update]

  # GET /usuarios/:usuario_id/actividads
  # GET /actividads
  # GET /actividads.json
  def index
    # Si hay usuario, de qué usuario vemos las actividades, sino todas
    @usuario = Usuario.find(params[:usuario_id]) if params[:usuario_id]
    @usuario ? @actividads = @usuario.actividads : @actividads = Actividad.all
  end

  # GET /actividads/1
  # GET /actividads/1.json
  def show
  end

  # GET /usuarios/:usuario_id/actividads/new
  # GET /actividads/new
  def new
    # Si hay usuario, de qué usuario vemos las actividades, sino todas
    @usuario = Usuario.find(params[:usuario_id]) if params[:usuario_id]
    @usuario ? @actividad = @usuario.actividads.build : @actividad = Actividad.new
  end

  # GET /actividads/1/edit
  def edit
  end

  # POST /actividads
  # POST /actividads.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Actividad was successfully created.' }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividads/1
  # PATCH/PUT /actividads/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividads/1
  # DELETE /actividads/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividads_url, notice: 'Actividad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

  # Confirms the correct user: itself or superadmin
  def usuario_actividad_o_admin
    if !current_user.superadmin?
      @actividad = Actividad.find(params[:id])
      @usuario = @actividad.usuario
      redirect_to(root_url) unless current_user?(@usuario)
    end
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:tipo_id, :actividad_id, :usuario_id, :nombre, :titulo, :autores, :presentador, :participantes, :fecha, :lugar, :origen_financiamiento, :comentario)
    end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/views/actividads/_form.html.erb
<%= form_for(@actividad) do |f| %>
  <% if @actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actividad.errors.count, "error") %> prohibited this actividad from being saved:</h2>

      <ul>
      <% @actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_id %><br>
    <%= f.collection_select :tipo_id, Tipo.all, :id, :tipo, :prompt => "Selecciona un tipo de proyecto" %>
  </div>
  <div class="field">
    <%= f.label :actividad_id %><br>
    <%= f.collection_select :actividad_id, TipoActividad.all, :id, :tipo, :prompt => "Selecciona un tipo de actividad" %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.collection_select :usuario_id, Usuario.all, :id, :nombre_completo, :prompt => "Selecciona el responsable de la actividad" %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autores %><br>
    <%= f.text_field :autores %>
  </div>
  <div class="field">
    <%= f.label :presentador %><br>
    <%= f.text_field :presentador %>
  </div>
  <div class="field">
    <%= f.label :participantes %><br>
    <%= f.text_field :participantes %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <% if @actividad.fecha %>
      <%= f.text_field :fecha,  class:"datepicker", :value => @actividad.fecha.strftime("%d/%m/%Y"), :data => {:provide => 'datepicker'} %>
    <% else %>
      <%= f.text_field :fecha,  class:"datepicker", :data => {:provide => 'datepicker'} %>
    <% end %>
  </div>
  <div class="field">
    <%# f.label :fecha %><br>
    <%# f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :lugar %><br>
    <%= f.text_field :lugar %>
  </div>
  <div class="field">
    <%= f.label :origen_financiamiento %><br>
    <%= f.text_field :origen_financiamiento %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({
       dateFormat : "dd MM yy",
       language: 'es'
    });
  });
</script>

app/views/actividads/_listing.html.erb
<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Actividad</th>
      <th>Docente</th>
      <th>Nombre Actividad</th>
      <th>Titulo</th>
      <th>Autores</th>
      <th>Presentador</th>
      <th>Participantes</th>
      <th>Fecha</th>
      <th>Lugar</th>
      <th>Origen financiamiento</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividads.each do |actividad| %>
      <tr>
        <td><%= actividad.tipo.tipo %></td>
        <td><%= actividad.tipo_actividad.tipo %></td>
        <td>
          <%= actividad.usuario.nombre_completo %>
          <%# actividad.usuario.nombre %>
        </td>
        <td><%= actividad.nombre %></td>
        <td><%= actividad.titulo %></td>
        <td><%= actividad.autores %></td>
        <td><%= actividad.presentador %></td>
        <td><%= actividad.participantes %></td>
        <td><%= actividad.fecha %></td>
        <td><%= actividad.lugar %></td>
        <td><%= actividad.origen_financiamiento %></td>
        <td><%= actividad.comentario %></td>
        <td><%= link_to 'Show', actividad %></td>
        <td><%= link_to 'Edit', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Destroy', actividad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actividad', new_actividad_path %>

app/views/actividads/_listing_usuario.html.erb
<h3>Actividades del docente 
  <%= @usuario.nombre_completo %>
</h3>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Actividad</th>
      <th>Nombre Actividad</th>
      <th>Titulo</th>
      <th>Autores</th>
      <th>Presentador</th>
      <th>Participantes</th>
      <th>Fecha</th>
      <th>Lugar</th>
      <th>Origen financiamiento</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividads.each do |actividad| %>
      <tr>
        <td><%= actividad.tipo.tipo %></td>
        <td><%= actividad.tipo_actividad.tipo %></td>
        <td><%= actividad.nombre %></td>
        <td><%= actividad.titulo %></td>
        <td><%= actividad.autores %></td>
        <td><%= actividad.presentador %></td>
        <td><%= actividad.participantes %></td>
        <td><%= actividad.fecha %></td>
        <td><%= actividad.lugar %></td>
        <td><%= actividad.origen_financiamiento %></td>
        <td><%= actividad.comentario %></td>
        <td><%= link_to 'Ver', actividad %></td>
        <td><%= link_to 'Editar', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Borrar', actividad, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Actividad', new_usuario_actividad_path %> | 
<%= link_to 'Todas las actividades', actividads_path %>

app/views/actividads/edit.html.erb
<h1>Editing actividad</h1>

<%= render 'form' %>

<%= link_to 'Show', @actividad %> |
<%= link_to 'Back', actividads_path %>

app/views/actividads/index.html.erb
<h1>Listing actividades</h1>

<% if @usuario %>
  <%= render 'listing_usuario' %>
<% else %>
  <%= render 'listing' %>
<% end %>

app/views/actividads/new.html.erb
<h1>New actividad</h1>

<%= render 'form' %>

<%= link_to 'Back', actividads_path %>

app/views/actividads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @actividad.tipo.tipo %>
</p>

<p>
  <strong>Actividad:</strong>
  <%= @actividad.tipo_actividad.tipo %>
</p>

<p>
  <strong>Docente:</strong>
  <%= @actividad.usuario.nombre_completo %> | 
  <%= link_to 'Actividades', usuario_actividads_path(@actividad.usuario) %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @actividad.nombre %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @actividad.titulo %>
</p>

<p>
  <strong>Autores:</strong>
  <%= @actividad.autores %>
</p>

<p>
  <strong>Presentador:</strong>
  <%= @actividad.presentador %>
</p>

<p>
  <strong>Participantes:</strong>
  <%= @actividad.participantes %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @actividad.fecha %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @actividad.lugar %>
</p>

<p>
  <strong>Origen financiamiento:</strong>
  <%= @actividad.origen_financiamiento %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @actividad.comentario %>
</p>

<%= link_to 'Editar', edit_actividad_path(@actividad) %> |
<%= link_to 'Volver', actividads_path %>