config/routes.rb
Rails.application.routes.draw do
  resources :actividads

  resources :tipos

  resources :tipo_actividads

  get 'sessions/new'

  get 'static_pages/home'
  get 'ayuda' => 'static_pages#ayuda'
  get 'acerca_de' => 'static_pages#acerca_de'

  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :cenurs

  resources :sedes

  resources :facultads

  resources :caracters

  resources :usuarios do
    resources :actividads, shallow: true
  end

  root 'static_pages#home'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many    :actividads
  belongs_to  :caracter
  belongs_to  :sede
  belongs_to  :facultad
  has_secure_password
  before_save { self.email = email.downcase }
  validates :nombre,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length:   { minimum: 6 }, allow_nil: true
   # self.per_page = 3

  # Returns the hash digest of the given string.
  def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # Nombre completo para los select
  def nombre_completo
    "#{nombre} #{apellido}"
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  include Authentication

  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy


  # GET /usuarios
  # GET /usuarios.json
  def index
    # @usuarios = Usuario.all
    @usuarios = Usuario.paginate(page: params[:page])

  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
	log_in @usuario
        flash[:success] = "¡Bienvenida a PDU App!"
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        flash[:success] = "Perfil actualizado"
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    flash[:success] = "Usuario borrado"
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Confirms a logged-in user.
#    def logged_in_user
#      unless logged_in?
#        store_location
#        flash[:danger] = "Por favor, conéctate."
#        redirect_to login_url
#      end
#    end
#
    # Confirms the correct user: itself or superadmin
    def correct_user
      if !current_user.superadmin?
        @usuario = Usuario.find(params[:id])
        redirect_to(root_url) unless current_user?(@usuario)
      end
    end
#
#    # Confirms an admin user.
#    def admin_user
#      redirect_to(root_url) unless current_user.superadmin?
#    end

    def set_usuario
      @usuario = Usuario.find(params[:id])
      @caracters = Caracter.all
      @sedes = Sede.all
      @facultads = Facultad.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :password, :password_confirmation, :email, :ci, :grado, :sede_id, :facultad_id, :anio_aprobado, :horas_servicio, :horas_sede, :dt, :viajero, :caracter_id, :calidad, :art9)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :ci %><br>
    <%= f.text_field :ci %>
  </div>
  <div class="field">
    <%= f.label :grado %><br>
    <%= f.number_field :grado %>
  </div>
  <div class="field">
    <%= f.label :sede_id %><br>
    <%# f.number_field :sede_id %>
    <%# f.collection_select :sede_id, @sedes, :id, :nombre, :prompt => "Selecciona una sede" %>
    <%= f.collection_select :sede_id, Sede.all, :id, :nombre, :prompt => "Selecciona una sede" %>
  </div>
  <div class="field">
    <%= f.label :facultad_id %><br>
    <%# f.number_field :facultad_id %>
    <%# f.collection_select :facultad_id, @facultads, :id, :nombre, :prompt => "Selecciona una facultad" %>
    <%= f.collection_select :facultad_id, Facultad.all, :id, :nombre, :prompt => "Selecciona una facultad" %>
  </div>
  <div class="field">
    <%= f.label :anio_aprobado %><br>
    <%= f.number_field :anio_aprobado %>
  </div>
  <div class="field">
    <%= f.label :horas_servicio %><br>
    <%= f.number_field :horas_servicio %>
  </div>
  <div class="field">
    <%= f.label :horas_sede %><br>
    <%= f.number_field :horas_sede %>
  </div>
  <div class="field">
    <%= f.label :dt %><br>
    <%= f.check_box :dt %>
  </div>
  <div class="field">
    <%= f.label :viajero %><br>
    <%= f.check_box :viajero %>
  </div>
  <div class="field">
    <%= f.label :caracter_id %><br>
    <%# f.number_field :caracter_id %>
    <%# f.collection_select :caracter_id, @caracters, :id, :descripcion, :prompt => "Select a prospect" %>
    <%= f.collection_select :caracter_id, Caracter.all, :id, :descripcion, :prompt => "Seleciona en la lista" %>
  </div>
  <div class="field">
    <%= f.label :calidad %><br>
    <%= f.text_field :calidad %>
  </div>
  <div class="field">
    <%= f.label :art9 %><br>
    <%= f.check_box :art9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

  <%= will_paginate %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>CI</th>
      <th>email</th>
      <th>Grado</th>
      <th>Sede</th>
      <th>Facultad</th>
      <th>Año aprobado</th>
      <th>Horas servicio</th>
      <th>Horas sede</th>
      <th>DT</th>
      <th>Viajero</th>
      <th>Caracter</th>
      <th>Calidad</th>
      <th>Art 9</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.nombre, usuario %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.ci %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.grado %></td>
        <td><%# usuario.sede_id %>
	    <%= usuario.sede.nombre %></td>
        <td><%# usuario.facultad_id %>
            <%= usuario.facultad.nombre %></td>
        <td><%= usuario.anio_aprobado %></td>
        <td><%= usuario.horas_servicio %></td>
        <td><%= usuario.horas_sede %></td>
        <td><%= usuario.dt %></td>
        <td><%= usuario.viajero %></td>
        <td><%# usuario.caracter_id %>
            <%= usuario.caracter.descripcion %></td>
        <td><%= usuario.calidad %></td>
        <td><%= usuario.art9 %></td>
        <td><%= link_to 'Ver', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td>
          <% if current_user.superadmin? && !current_user?(usuario) %>
            <%= link_to 'Borrar', usuario, method: :delete, data: { confirm: '¿Estás seguro?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= will_paginate %>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @usuario.ci %>
</p>

<p>
  <strong>Grado:</strong>
  <%= @usuario.grado %>
</p>

<p>
  <strong>Sede:</strong>
  <%= @usuario.sede_id %>
  <%= @usuario.sede.nombre %>
</p>

<p>
  <strong>Facultad:</strong>
  <%= @usuario.facultad_id %>
  <%= @usuario.facultad.nombre %>
</p>

<p>
  <strong>Anio aprobado:</strong>
  <%= @usuario.anio_aprobado %>
</p>

<p>
  <strong>Horas servicio:</strong>
  <%= @usuario.horas_servicio %>
</p>

<p>
  <strong>Horas sede:</strong>
  <%= @usuario.horas_sede %>
</p>

<p>
  <strong>Dt:</strong>
  <%= @usuario.dt %>
</p>

<p>
  <strong>Viajero:</strong>
  <%= @usuario.viajero %>
</p>

<p>
  <strong>Caracter:</strong>
  <%= @usuario.caracter_id %>
  <%= @usuario.caracter.descripcion %>
</p>

<p>
  <strong>Calidad:</strong>
  <%= @usuario.calidad %>
</p>

<p>
  <strong>Art9:</strong>
  <%= @usuario.art9 %>
</p>

<%= link_to 'Actividades', usuario_actividads_path(@usuario) %> |
<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Volver', usuarios_path %>