config/routes.rb
Rails.application.routes.draw do
  resources :actividads

  resources :tipos

  resources :tipo_actividads

  get 'sessions/new'

  get 'static_pages/home'
  get 'ayuda' => 'static_pages#ayuda'
  get 'acerca_de' => 'static_pages#acerca_de'

  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :cenurs

  resources :sedes

  resources :facultads

  resources :caracters

  resources :usuarios do
    resources :actividads, shallow: true
  end

  root 'static_pages#home'

end

app/models/facultad.rb
class Facultad < ActiveRecord::Base
  has_many :usuarios
end

app/controllers/facultads_controller.rb
class FacultadsController < ApplicationController
  include Authentication

  before_action :set_facultad, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  # GET /facultads
  # GET /facultads.json
  def index
    @facultads = Facultad.all
  end

  # GET /facultads/1
  # GET /facultads/1.json
  def show
  end

  # GET /facultads/new
  def new
    @facultad = Facultad.new
  end

  # GET /facultads/1/edit
  def edit
  end

  # POST /facultads
  # POST /facultads.json
  def create
    @facultad = Facultad.new(facultad_params)

    respond_to do |format|
      if @facultad.save
        format.html { redirect_to @facultad, notice: 'Facultad was successfully created.' }
        format.json { render :show, status: :created, location: @facultad }
      else
        format.html { render :new }
        format.json { render json: @facultad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facultads/1
  # PATCH/PUT /facultads/1.json
  def update
    respond_to do |format|
      if @facultad.update(facultad_params)
        format.html { redirect_to @facultad, notice: 'Facultad was successfully updated.' }
        format.json { render :show, status: :ok, location: @facultad }
      else
        format.html { render :edit }
        format.json { render json: @facultad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facultads/1
  # DELETE /facultads/1.json
  def destroy
    @facultad.destroy
    respond_to do |format|
      format.html { redirect_to facultads_url, notice: 'Facultad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facultad
      @facultad = Facultad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facultad_params
      params.require(:facultad).permit(:nombre, :web, :comentario)
    end
end

app/helpers/facultads_helper.rb
module FacultadsHelper
end

app/views/facultads/_form.html.erb
<%= form_for(@facultad) do |f| %>
  <% if @facultad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facultad.errors.count, "error") %> prohibited this facultad from being saved:</h2>

      <ul>
      <% @facultad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facultads/edit.html.erb
<h1>Editing facultad</h1>

<%= render 'form' %>

<%= link_to 'Show', @facultad %> |
<%= link_to 'Back', facultads_path %>

app/views/facultads/index.html.erb
<h1>Listing facultads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Web</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facultads.each do |facultad| %>
      <tr>
        <td><%= facultad.nombre %></td>
        <td><%= facultad.web %></td>
        <td><%= facultad.comentario %></td>
        <td><%= link_to 'Show', facultad %></td>
        <td><%= link_to 'Edit', edit_facultad_path(facultad) %></td>
        <td><%= link_to 'Destroy', facultad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facultad', new_facultad_path %>

app/views/facultads/new.html.erb
<h1>New facultad</h1>

<%= render 'form' %>

<%= link_to 'Back', facultads_path %>

app/views/facultads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @facultad.nombre %>
</p>

<p>
  <strong>Web:</strong>
  <%= @facultad.web %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @facultad.comentario %>
</p>

<%= link_to 'Edit', edit_facultad_path(@facultad) %> |
<%= link_to 'Back', facultads_path %>