config/routes.rb
Rails.application.routes.draw do
  resources :actividads

  resources :tipos

  resources :tipo_actividads

  get 'sessions/new'

  get 'static_pages/home'
  get 'ayuda' => 'static_pages#ayuda'
  get 'acerca_de' => 'static_pages#acerca_de'

  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :cenurs

  resources :sedes

  resources :facultads

  resources :caracters

  resources :usuarios do
    resources :actividads, shallow: true
  end

  root 'static_pages#home'

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to  :usuario
  belongs_to  :tipo
  belongs_to  :tipo_actividad, :foreign_key => 'actividad_id'
validates :tipo_id, presence: true
validates :actividad_id, presence: true
validates :usuario_id, presence: true
validates :nombre, presence: true
end

app/models/caracter.rb
class Caracter < ActiveRecord::Base
  has_many :usuarios
end

app/models/cenur.rb
class Cenur < ActiveRecord::Base
  has_many :sedes
end

app/models/facultad.rb
class Facultad < ActiveRecord::Base
  has_many :usuarios
end

app/models/sede.rb
class Sede < ActiveRecord::Base
  belongs_to  :cenur
  has_many :usuarios
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  has_many :actividads
end

app/models/tipo_actividad.rb
class TipoActividad < ActiveRecord::Base
  has_many :actividads
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many    :actividads
  belongs_to  :caracter
  belongs_to  :sede
  belongs_to  :facultad
  has_secure_password
  before_save { self.email = email.downcase }
  validates :nombre,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length:   { minimum: 6 }, allow_nil: true
   # self.per_page = 3

  # Returns the hash digest of the given string.
  def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # Nombre completo para los select
  def nombre_completo
    "#{nombre} #{apellido}"
  end
end

app/controllers/sedes_controller.rb
class SedesController < ApplicationController
  include Authentication

  before_action :set_sede, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :edit, :update, :destroy]

  # GET /sedes
  # GET /sedes.json
  def index
    @sedes = Sede.all
  end

  # GET /sedes/1
  # GET /sedes/1.json
  def show
  end

  # GET /sedes/new
  def new
    @sede = Sede.new
  end

  # GET /sedes/1/edit
  def edit
  end

  # POST /sedes
  # POST /sedes.json
  def create
    @sede = Sede.new(sede_params)

    respond_to do |format|
      if @sede.save
        format.html { redirect_to @sede, notice: 'Sede was successfully created.' }
        format.json { render :show, status: :created, location: @sede }
      else
        format.html { render :new }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sedes/1
  # PATCH/PUT /sedes/1.json
  def update
    respond_to do |format|
      if @sede.update(sede_params)
        format.html { redirect_to @sede, notice: 'Sede was successfully updated.' }
        format.json { render :show, status: :ok, location: @sede }
      else
        format.html { render :edit }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sedes/1
  # DELETE /sedes/1.json
  def destroy
    @sede.destroy
    respond_to do |format|
      format.html { redirect_to sedes_url, notice: 'Sede was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sede
      @sede = Sede.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sede_params
      params.require(:sede).permit(:nombre, :web, :cenur_id, :comentario)
    end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  include Authentication

  before_action :set_tipo, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:tipo)
    end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Información de los PDU"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/caracters_helper.rb
module CaractersHelper
end

app/helpers/cenurs_helper.rb
module CenursHelper
end

app/helpers/facultads_helper.rb
module FacultadsHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(usuario)
    session[:usuario_id] = usuario.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= Usuario.find_by(id: session[:usuario_id])
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:usuario_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "PDU App", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Ayuda",   ayuda_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Personas", usuarios_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Mi cuenta <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Mi perfil", current_user %></li>
                  <li><%= link_to "Mis datos", edit_usuario_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>